# Generated by Django 4.2.4 on 2023-08-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_usertoken'),
        ('team', '0010_alter_team_team_key_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_name', models.CharField(max_length=100)),
                ('notification_content', models.TextField(null=True)),
                ('notification_create_time', models.DateTimeField(auto_now_add=True)),
                ('notification_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
                ('notification_receiver', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_content', models.TextField()),
                ('cm_create_time', models.DateTimeField(auto_now_add=True)),
                ('cm_isat', models.BooleanField(default=False)),
                ('cm_at_all', models.BooleanField(default=False)),
                ('cm_at', models.ManyToManyField(to='team.teammember')),
                ('cm_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
