# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_content', models.TextField()),
                ('cm_create_time', models.DateTimeField(auto_now_add=True)),
                ('cm_isat', models.BooleanField(default=False)),
                ('cm_at_all', models.BooleanField(default=False)),
                ('cm_type', models.CharField(default='message', max_length=100)),
                ('cm_private_connect_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_name', models.CharField(max_length=100)),
                ('notification_content', models.TextField(null=True)),
                ('notification_create_time', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('at', '@信息'), ('application', '申请信息'), ('system', '系统信息')], default='system', max_length=20)),
                ('notification_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
