# Generated by Django 4.2.4 on 2023-08-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_avatar'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='user.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_receiver',
            field=models.ManyToManyField(related_name='receiver', to='user.user'),
        ),
    ]
