# Generated by Django 4.2.4 on 2023-08-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
        ('message', '0001_initial'),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='user.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.chatmessage'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='user.user'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cm_at',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cm_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cm_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
