# Generated by Django 4.2.4 on 2023-08-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_expire_time'),
        ('message', '0002_alter_notification_notification_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cm_type',
            field=models.CharField(default='message', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('at', '@信息'), ('application', '申请信息'), ('system', '系统信息')], default='system', max_length=20),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='user.user'),
        ),
    ]
