# Generated by Django 4.2.4 on 2023-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_leavehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('at', '@信息'), ('application', '申请信息'), ('system', '系统信息'), ('document', '文档@')], default='system', max_length=20),
        ),
    ]
