# Generated by Django 4.2.4 on 2023-08-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_saveddocument_sd_file'),
        ('message', '0003_chatmessage_cm_type_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cm_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file'),
        ),
    ]
