# Generated by Django 4.2.4 on 2023-08-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_chatmessage_cm_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.chatmessage'),
        ),
    ]
