# Generated by Django 4.2.4 on 2023-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_notification_notification_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cm_private_connect_id',
            field=models.IntegerField(default=0),
        ),
    ]
