# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_description', models.TextField(null=True)),
                ('document_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('document_create_time', models.DateTimeField(auto_now_add=True)),
                ('document_complete_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('editor_name', models.CharField(max_length=100)),
                ('editor_current_position', models.IntegerField(default=0)),
                ('editor_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
        ),
    ]
