# Generated by Django 4.2.4 on 2023-08-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_recycle', models.BooleanField(default=False)),
                ('document_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_content', models.FileField(max_length=255, null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('prototype_id', models.AutoField(primary_key=True, serialize=False)),
                ('prototype_name', models.CharField(max_length=100)),
                ('prototype_file', models.FileField(max_length=255, upload_to='prototype/')),
                ('prototype_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('prototype_change_time', models.DateTimeField(null=True)),
                ('prototype_recycle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_editable', models.BooleanField(default=False)),
                ('template_file', models.FileField(max_length=255, upload_to='template/')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False)),
                ('sd_file', models.FileField(max_length=255, null=True, upload_to='SavedDocument/')),
                ('sd_saved_time', models.DateTimeField(auto_now_add=True)),
                ('sd_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
        ),
    ]
