# Generated by Django 4.2.1 on 2023-08-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_rename_chat_creator_chat_chat_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_description', models.TextField(null=True)),
                ('document_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('document_create_time', models.DateTimeField(auto_now_add=True)),
                ('document_complete_date', models.DateTimeField(null=True)),
                ('document_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('editor_name', models.CharField(max_length=100)),
                ('editor_current_position', models.IntegerField(default=0)),
                ('editor_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_editors',
            field=models.ManyToManyField(related_name='document_members', to='document.editor'),
        ),
    ]
