# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('project', '0001_initial'),
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='prototype_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='prototype_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_allowed_editors',
            field=models.ManyToManyField(to='user.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_saves',
            field=models.ManyToManyField(to='document.saveddocument'),
        ),
    ]
