# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_editors',
            field=models.ManyToManyField(related_name='document_members', to='document.editor'),
        ),
    ]
