# Generated by Django 4.2.4 on 2023-08-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_allowed_editors',
        ),
        migrations.AddField(
            model_name='document',
            name='document_allow_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='document_allow_edit',
            field=models.BooleanField(default=False),
        ),
    ]
