# Generated by Django 4.2.1 on 2023-08-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_team_key_team_team_key_expire_time_and_more'),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False)),
                ('sd_description', models.TextField(null=True)),
                ('sd_saved_time', models.DateTimeField(auto_now_add=True)),
                ('sd_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
                ('sd_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_saves',
            field=models.ManyToManyField(to='document.saveddocument'),
        ),
    ]
