# Generated by Django 4.2.4 on 2023-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_saveddocument_document_document_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_avatar',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/document/'),
        ),
    ]
