# Generated by Django 4.2.4 on 2023-08-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('document', '0003_remove_document_document_allowed_editors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_project',
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('directory_id', models.AutoField(primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=100)),
                ('directory_document', models.ManyToManyField(to='document.document')),
                ('directory_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.directory'),
        ),
    ]
