# Generated by Django 4.2.4 on 2023-08-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_project_document_and_more'),
        ('document', '0004_remove_document_document_project_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
