# Generated by Django 4.2.4 on 2023-08-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_remove_teamchat_tc_name'),
        ('user', '0004_alter_user_user_expire_time'),
        ('document', '0004_alter_document_document_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_content', models.FileField(max_length=255, null=True, upload_to='file/')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_avatar',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_complete_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_create_time',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_creator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_editors',
        ),
        migrations.RemoveField(
            model_name='saveddocument',
            name='sd_creator',
        ),
        migrations.RemoveField(
            model_name='saveddocument',
            name='sd_description',
        ),
        migrations.AddField(
            model_name='document',
            name='document_allowed_editors',
            field=models.ManyToManyField(to='user.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
