# Generated by Django 4.2.4 on 2023-08-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_document_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_project',
        ),
    ]
