# Generated by Django 4.2.4 on 2023-08-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_file_remove_document_document_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddocument',
            name='sd_file',
            field=models.FileField(max_length=255, null=True, upload_to='SavedDocument/'),
        ),
    ]
