# Generated by Django 4.2.4 on 2023-08-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_remove_document_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='prototype_components',
            field=models.JSONField(default=''),
        ),
    ]
