# Generated by Django 4.2.4 on 2023-08-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_project_avatar'),
        ('document', '0007_prototype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_team',
        ),
        migrations.RemoveField(
            model_name='prototype',
            name='prototype_team',
        ),
        migrations.AddField(
            model_name='document',
            name='document_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='prototype_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
