# Generated by Django 4.2.4 on 2023-08-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_prototype_prototype_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='prototype_components',
            field=models.JSONField(default=None, null=True),
        ),
    ]
