# Generated by Django 4.2.4 on 2023-08-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_prototype_prototype_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='prototype_file',
        ),
    ]
