# Generated by Django 4.2.4 on 2023-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_remove_document_document_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_create_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="document_editable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="document_recycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prototype",
            name="prototype_change_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="prototype",
            name="prototype_create_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="prototype",
            name="prototype_recycle",
            field=models.BooleanField(default=False),
        ),
    ]
