# Generated by Django 4.2.4 on 2023-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_remove_prototype_prototype_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddocument',
            name='sd_file',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.JSONField(default=None, null=True),
        ),
    ]
