# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=100)),
                ('chat_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_description', models.TextField(null=True)),
                ('team_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('team_tel', models.TextField(null=True)),
                ('team_create_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_user_nickname', models.CharField(max_length=100)),
                ('tm_user_permissions', models.CharField(choices=[('creator', '创建者'), ('manager', '管理员'), ('member', '成员')], default='member', max_length=20)),
                ('tm_user_join_time', models.DateTimeField(null=True)),
                ('tm_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
