# Generated by Django 4.2.1 on 2023-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_password', models.CharField(max_length=20)),
                ('team_signature', models.TextField(null=True)),
                ('team_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('team_company', models.TextField(null=True)),
                ('team_email', models.EmailField(blank=True, default=None, max_length=50)),
                ('team_tel', models.TextField(null=True)),
                ('team_expire_time', models.IntegerField(default=30, null=True)),
            ],
        ),
    ]
