# Generated by Django 4.2.1 on 2023-08-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_signature',
            new_name='team_description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_expire_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_password',
        ),
        migrations.AddField(
            model_name='team',
            name='team_create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_projects',
            field=models.ManyToManyField(null=True, to='project.project'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=100)),
                ('chat_signature', models.TextField(null=True)),
                ('chat_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('chat_tel', models.TextField(null=True)),
                ('chat_admins', models.ManyToManyField(null=True, related_name='chat_admins', to='user.user')),
                ('chat_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('chat_members', models.ManyToManyField(null=True, related_name='chat_members', to='user.user')),
                ('chat_projects', models.ManyToManyField(null=True, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_user_nickname', models.CharField(max_length=100)),
                ('tm_user_permissions', models.CharField(choices=[('creator', '创建者'), ('manager', '管理员'), ('member', '成员')], default='member', max_length=20)),
                ('tm_user_join_time', models.DateTimeField(null=True)),
                ('tm_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('tm_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('tm_team_id', 'tm_user_id')},
            },
        ),
    ]
