# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_initial'),
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tm_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_chats',
            field=models.ManyToManyField(to='team.chat'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_projects',
            field=models.ManyToManyField(to='project.project'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_admins',
            field=models.ManyToManyField(related_name='chat_admins', to='team.teammember'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_members',
            field=models.ManyToManyField(related_name='chat_members', to='team.teammember'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('tm_team_id', 'tm_user_id')},
        ),
    ]
