# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0002_initial'),
        ('project', '0002_initial'),
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tm_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='teamchat',
            name='tc_history',
            field=models.ManyToManyField(to='message.chatmessage'),
        ),
        migrations.AddField(
            model_name='teamchat',
            name='tc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AddField(
            model_name='teamapplicant',
            name='ta_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AddField(
            model_name='teamapplicant',
            name='ta_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_applicants',
            field=models.ManyToManyField(to='team.teamapplicant'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teamchat'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_projects',
            field=models.ManyToManyField(to='project.project'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='pc_history',
            field=models.ManyToManyField(to='message.chatmessage'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='pc_members',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='gc_history',
            field=models.ManyToManyField(to='message.chatmessage'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='gc_members',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('tm_team_id', 'tm_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='teamapplicant',
            unique_together={('ta_team_id', 'ta_user_id')},
        ),
    ]
