# Generated by Django 4.2.1 on 2023-08-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_company_user_user_created_teams_and_more'),
        ('project', '0002_alter_project_project_members'),
        ('team', '0002_rename_team_signature_team_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_admins',
            field=models.ManyToManyField(related_name='chat_admins', to='user.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_members',
            field=models.ManyToManyField(related_name='chat_members', to='user.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_projects',
            field=models.ManyToManyField(to='project.project'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_projects',
            field=models.ManyToManyField(to='project.project'),
        ),
    ]
