# Generated by Django 4.2.4 on 2023-08-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='gc_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gc_creator', to='team.teammember'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='gc_members',
            field=models.ManyToManyField(related_name='gc_members', to='team.teammember'),
        ),
    ]
