# Generated by Django 4.2.1 on 2023-08-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertoken'),
        ('team', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_key_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='TeamApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_apply_time', models.DateTimeField(null=True)),
                ('ta_message', models.CharField(max_length=100)),
                ('ta_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('ta_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('ta_team_id', 'ta_user_id')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='team_applicants',
            field=models.ManyToManyField(to='team.teamapplicant'),
        ),
    ]
