# Generated by Django 4.2.1 on 2023-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_team_key_team_team_key_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tm_user_join_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
