# Generated by Django 4.2.1 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_chat_chat_admins_alter_chat_chat_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_creator',
            new_name='chat_owner',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_projects',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_signature',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_tel',
        ),
        migrations.AddField(
            model_name='team',
            name='team_chats',
            field=models.ManyToManyField(to='team.chat'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_admins',
            field=models.ManyToManyField(related_name='chat_admins', to='team.teammember'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_members',
            field=models.ManyToManyField(related_name='chat_members', to='team.teammember'),
        ),
    ]
