# Generated by Django 4.2.4 on 2023-08-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_groupchat_gc_creator_alter_groupchat_gc_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='gc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
