# Generated by Django 4.2.4 on 2023-08-25 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_alter_team_team_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_create_time",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
