# Generated by Django 4.2.4 on 2023-08-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_alter_teammember_tm_user_join_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_key_expire_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
