# Generated by Django 4.2.4 on 2023-08-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('user', '0002_usertoken'),
        ('team', '0010_alter_team_team_key_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_history', models.ManyToManyField(to='message.chatmessage')),
                ('pc_members', models.ManyToManyField(to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_name', models.CharField(max_length=100)),
                ('tc_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('tc_history', models.ManyToManyField(to='message.chatmessage')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_chats',
        ),
        migrations.AlterField(
            model_name='teamapplicant',
            name='ta_apply_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamapplicant',
            name='ta_message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AddField(
            model_name='teamchat',
            name='tc_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teamchat'),
        ),
    ]
