# Generated by Django 4.2.4 on 2023-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_privatechat_teamchat_remove_team_team_chats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamchat',
            name='tc_avatar',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_avatar',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/team/'),
        ),
    ]
