# Generated by Django 4.2.4 on 2023-08-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_remove_teamchat_tc_avatar_alter_team_team_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamchat',
            name='tc_name',
        ),
    ]
