# Generated by Django 4.2.4 on 2023-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_chatmessage_cm_private_connect_id'),
        ('team', '0013_remove_teamchat_tc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='pc_members',
            field=models.ManyToManyField(to='team.teammember'),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('gc_id', models.AutoField(primary_key=True, serialize=False)),
                ('gc_name', models.CharField(max_length=30)),
                ('gc_history', models.ManyToManyField(to='message.chatmessage')),
                ('gc_members', models.ManyToManyField(to='team.teammember')),
            ],
        ),
    ]
