# Generated by Django 4.2.1 on 2023-08-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(null=True)),
                ('project_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('project_create_time', models.DateTimeField(null=True)),
                ('tm_user_permissions', models.CharField(choices=[('creator', '创建者'), ('manager', '管理员'), ('member', '成员')], default='member', max_length=20)),
                ('project_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('project_members', models.ManyToManyField(null=True, related_name='project_members', to='user.user')),
            ],
        ),
    ]
