# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(null=True)),
                ('project_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('project_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_complete_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=100)),
                ('requirement_description', models.TextField(null=True)),
                ('requirement_create_time', models.DateTimeField(auto_now_add=True)),
                ('requirement_complete_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
