# Generated by Django 4.2.4 on 2023-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(null=True)),
                ('project_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/project/')),
                ('project_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_estimated_start_time', models.DateTimeField(null=True)),
                ('project_estimated_end_time', models.DateTimeField(null=True)),
                ('project_end_time', models.DateTimeField(null=True)),
                ('project_start_time', models.DateTimeField(null=True)),
                ('project_editable', models.BooleanField(default=False)),
                ('project_status', models.CharField(choices=[('not_started', '未开始'), ('doing', '进行中'), ('finished', '已完成')], default='not_started', max_length=20)),
                ('project_recycle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=100)),
                ('requirement_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('requirement_estimated_start_time', models.DateTimeField(null=True)),
                ('requirement_estimated_end_time', models.DateTimeField(null=True)),
                ('requirement_end_time', models.DateTimeField(null=True)),
                ('requirement_start_time', models.DateTimeField(null=True)),
                ('requirement_status', models.CharField(choices=[('not_started', '未开始'), ('doing', '进行中'), ('finished', '已完成')], default='not_started', max_length=20)),
            ],
        ),
    ]
