# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('team', '0001_initial'),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_document',
            field=models.ManyToManyField(to='document.document'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_prototype',
            field=models.ManyToManyField(to='document.prototype'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_requirement',
            field=models.ManyToManyField(to='project.requirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
