# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_members',
            field=models.ManyToManyField(related_name='requirement_members', to='team.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='project_members', to='team.teammember'),
        ),
    ]
