# Generated by Django 4.2.1 on 2023-08-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_company_user_user_created_teams_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='project_members', to='user.user'),
        ),
    ]
