# Generated by Django 4.2.1 on 2023-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_editable',
            field=models.BooleanField(default=True),
        ),
    ]
