# Generated by Django 4.2.1 on 2023-08-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_chat_creator_chat_chat_owner_and_more'),
        ('project', '0002_alter_project_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tm_user_permissions',
        ),
        migrations.AddField(
            model_name='project',
            name='project_complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(related_name='project_members', to='team.teammember'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=100)),
                ('requirement_description', models.TextField(null=True)),
                ('requirement_create_time', models.DateTimeField(auto_now_add=True)),
                ('requirement_complete_time', models.DateTimeField(null=True)),
                ('requirement_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember')),
                ('requirement_members', models.ManyToManyField(related_name='requirement_members', to='team.teammember')),
            ],
        ),
    ]
