# Generated by Django 4.2.4 on 2023-08-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_project_project_members_project_project_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_complete_date",
            new_name="project_end_time",
        ),
        migrations.RenameField(
            model_name="requirement",
            old_name="requirement_complete_time",
            new_name="requirement_end_time",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="requirement_description",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="requirement_members",
        ),
        migrations.AddField(
            model_name="project",
            name="project_estimated_end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_estimated_start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_recycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="project_requirement",
            field=models.ManyToManyField(to="project.requirement"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[("not_started", "未开始"), ("doing", "进行中"), ("finished", "已完成")],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_estimated_end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_estimated_start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_status",
            field=models.CharField(
                choices=[("not_started", "未开始"), ("doing", "进行中"), ("finished", "已完成")],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="requirement_create_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
