# Generated by Django 4.2.4 on 2023-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_directory_directory_recycle_template_template_type'),
        ('project', '0004_project_project_recycle_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_recycle_directory',
            field=models.ManyToManyField(related_name='recycled_directory', to='document.directory'),
        ),
    ]
