# Generated by Django 4.2.4 on 2023-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_remove_document_document_team_and_more'),
        ('project', '0006_alter_project_project_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_document',
            field=models.ManyToManyField(to='document.document'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_prototype',
            field=models.ManyToManyField(to='document.prototype'),
        ),
    ]
