<<<<<<< Updated upstream
# Generated by Django 4.2.4 on 2023-08-30 16:15
=======
# Generated by Django 4.2.4 on 2023-08-30 20:01
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
        ("project", "0007_project_project_document_project_project_prototype"),
=======
        ('project', '0007_project_project_document_project_project_prototype'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AlterField(
<<<<<<< Updated upstream
            model_name="project",
            name="project_editable",
=======
            model_name='project',
            name='project_editable',
>>>>>>> Stashed changes
            field=models.BooleanField(default=False),
        ),
    ]
