# Generated by Django 4.2.4 on 2023-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_project_project_document_project_project_prototype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_editable",
            field=models.BooleanField(default=False),
        ),
    ]
