# Generated by Django 4.2.1 on 2023-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_real_name', models.CharField(max_length=100, null=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_signature', models.TextField(null=True)),
                ('user_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/')),
                ('user_email', models.EmailField(blank=True, default=None, max_length=50)),
                ('user_tel', models.TextField(null=True)),
                ('user_expire_time', models.IntegerField(default=30, null=True)),
                ('user_visible', models.BooleanField(default=True)),
                ('user_created_projects', models.ManyToManyField(to='project.project')),
                ('user_created_teams', models.ManyToManyField(related_name='created_by_users', to='team.team')),
                ('user_joined_teams', models.ManyToManyField(related_name='joined_by_users', to='team.team')),
                ('user_managed_teams', models.ManyToManyField(related_name='managed_by_users', to='team.team')),
            ],
        ),
    ]
