# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('project', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_real_name', models.CharField(max_length=100, null=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_signature', models.TextField(null=True)),
                ('user_avatar', models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/user/')),
                ('user_email', models.EmailField(blank=True, default=None, max_length=50)),
                ('user_tel', models.TextField(null=True)),
                ('user_expire_time', models.IntegerField(default=2880, null=True)),
                ('user_visible', models.BooleanField(default=True)),
                ('user_created_projects', models.ManyToManyField(to='project.project')),
                ('user_created_teams', models.ManyToManyField(related_name='created_by_users', to='team.team')),
                ('user_joined_teams', models.ManyToManyField(related_name='joined_by_users', to='team.team')),
                ('user_managed_teams', models.ManyToManyField(related_name='managed_by_users', to='team.team')),
                ('user_notification_list', models.ManyToManyField(to='message.notification')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('expire_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
