# Generated by Django 4.2.1 on 2023-08-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_team_signature_team_team_description_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_company',
        ),
        migrations.AddField(
            model_name='user',
            name='user_created_teams',
            field=models.ManyToManyField(related_name='created_by_users', to='team.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_joined_teams',
            field=models.ManyToManyField(related_name='joined_by_users', to='team.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
