# Generated by Django 4.2.1 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_chat_creator_chat_chat_owner_and_more'),
        ('project', '0003_remove_project_tm_user_permissions_and_more'),
        ('user', '0002_remove_user_user_company_user_user_created_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_created_projects',
            field=models.ManyToManyField(to='project.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_managed_teams',
            field=models.ManyToManyField(related_name='managed_by_users', to='team.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_visible',
            field=models.BooleanField(default=True),
        ),
    ]
