# Generated by Django 4.2.4 on 2023-08-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_expire_time',
            field=models.IntegerField(default=2880, null=True),
        ),
    ]
