# Generated by Django 4.2 on 2023-08-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_user_created_projects_user_user_managed_teams"),
        ("user", "0003_user_user_created_projects_user_user_managed_teams_and_more"),
    ]

    operations = []
