# Generated by Django 4.2.4 on 2023-08-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_chatmessage_cm_type_notification_notification_type_and_more'),
        ('user', '0004_alter_user_user_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_notification_list',
            field=models.ManyToManyField(to='message.notification'),
        ),
    ]
