name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /root/UnknowProject/UnknownProject_backend
            pkill -f "python manage.py runserver 127.0.0.1:5566"
            git pull
            pip install -r requirements.txt
            sleep 3
            python manage.py runserver 127.0.0.1:5566 &

            sudo service nginx restart
            

